import { BookmarkedStory } from '../../models/story.model';

export const BOOKMARKED_STORIES: BookmarkedStory[] = [
  {
    title: `you know i'm such a fool for you`,
    author: `qthedoor`,
    lastUpdated: `19 Apr 2021`,
    bookmarks: 100,
    chapters: 11,
    words: 40443,
  },
  {
    title: `Heat Vision`,
    author: `lears_daughter`,
    lastUpdated: `10 Dec 2016`,
    bookmarks: 101,
    chapters: 1,
    words: 7442,
  },
  {
    title: `Reinvention`,
    author: `lears_daughter`,
    lastUpdated: `04 Feb 2024`,
    bookmarks: 71,
    chapters: 1,
    words: 16495,
  },
  {
    title: `what lingers in the eaves`,
    author: `QuickYoke`,
    lastUpdated: `29 Jul 2017`,
    bookmarks: 52,
    chapters: 1,
    words: 7243,
  },
  {
    title: `Snapshots for the future`,
    author: `puppybusby`,
    lastUpdated: `26 Dec 2020`,
    bookmarks: 335,
    chapters: 3,
    words: 26172,
  },
  {
    title: `Missing Piece`,
    author: `Castibella_Shipper_of_the_Lord`,
    lastUpdated: `06 Feb 2021`,
    bookmarks: 88,
    chapters: 2,
    words: 4881,
  },
  {
    title: `Do a Flip`,
    author: `sunsafe`,
    lastUpdated: `26 Mar 2023`,
    bookmarks: 760,
    chapters: 7,
    words: 76032,
  },
  {
    title: `desperate times, desperate measures`,
    author: `AdeleDazeem`,
    lastUpdated: `11 Dec 2022`,
    bookmarks: 864,
    chapters: 3,
    words: 18207,
  },
  {
    title: `you're in my life (can't get you off my mind)`,
    author: `TheGoatWithAPen`,
    lastUpdated: `03 Jan 2023`,
    bookmarks: 279,
    chapters: 1,
    words: 15757,
  },
  {
    title: `a nun, a halo bearer, and an interdimensional pseudo-demon walk into an apartment`,
    author: `nirav`,
    lastUpdated: `20 Nov 2022`,
    bookmarks: 452,
    chapters: 3,
    words: 13422,
  },
  {
    title: `we can be brilliant`,
    author: `sxftmelody`,
    lastUpdated: `18 Nov 2022`,
    bookmarks: 1175,
    chapters: 1,
    words: 21305,
  },
  {
    title: `who needs comfortable love`,
    author: `the_ominous_owl`,
    lastUpdated: `17 Mar 2023`,
    bookmarks: 1242,
    chapters: 9,
    words: 77746,
  },
  {
    title: `The Love of Fair Olivia`,
    author: `partypaprika`,
    lastUpdated: `06 Feb 2017`,
    bookmarks: 178,
    chapters: 1,
    words: 5241,
  },
  {
    title: `Make You Smile `,
    author: `Tasu`,
    lastUpdated: `12 Jan 2023`,
    bookmarks: 53,
    chapters: 1,
    words: 2120,
  },
  {
    title: `The Scientific Investigation of the Infatuated Princess and the Genius Research Assistant`,
    author: `SailorPortia`,
    lastUpdated: `02 Feb 2023`,
    bookmarks: 60,
    chapters: 1,
    words: 3329,
  },
  {
    title: `The Addamsation of Enid Sinclair`,
    author: `whitebeltwriter`,
    lastUpdated: `17 Feb 2023`,
    bookmarks: 979,
    chapters: 5,
    words: 12207,
  },
  {
    title: `raven in the den, wolf in the nest`,
    author: `Barbara_Lazuli`,
    lastUpdated: `30 Mar 2023`,
    bookmarks: 1258,
    chapters: 4,
    words: 39321,
  },
  {
    title: `you could be the one that i keep`,
    author: `overnights`,
    lastUpdated: `30 Dec 2022`,
    bookmarks: 629,
    chapters: 1,
    words: 20980,
  },
  {
    title: `Reset`,
    author: `Eggplant_Crusader`,
    lastUpdated: `13 Nov 2022`,
    bookmarks: 2244,
    chapters: 1,
    words: 3242,
  },
  {
    title: `falling like the stars`,
    author: `Extrinsical`,
    lastUpdated: `10 Jun 2019`,
    bookmarks: 91,
    chapters: 1,
    words: 13281,
  },
];
